# Generated by Django 5.2.8 on 2025-11-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(default='حصة', max_length=100)),
                ('duration', models.IntegerField(default=45)),
                ('is_break', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='الثانوية الثالثة عشر بعرعر', max_length=255)),
                ('next_break_after', models.IntegerField(default=2)),
                ('break_duration', models.IntegerField(default=15)),
                ('time_between_lessons', models.IntegerField(default=5)),
                ('dhuhr_prayer', models.TimeField(default='12:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
